modLoader = "javafml"
loaderVersion = "[34,)"
license = "GNU GPLv3"
[[mods]]
modId = "mobfarmutilities"
version = "${version}"
displayName = "Mob Farm Utilities"
issueTrackerURL = "https://github.com/yzl210/MobFarmUtilities/issues"
authors = "yzl210"
description = '''
Add some useful mob farm utilities
'''

